package view;

/**
 *
 * @author Luis
 */

import model.ClinicaManager;
import model.Paciente;
import model.Medico;
import model.Administrativomodel;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;


public class Administrativo extends javax.swing.JFrame {
    
    private ClinicaManager manager;
    public Administrativo() {
        initComponents();
        this.manager = new ClinicaManager();
        cargarDatosIniciales();
    }
    
    //########## SE CARGAN DATOS DE PACIENTES
    private void cargarDatosIniciales() {
        try {
        List<Paciente> pacientes = manager.listarPacientes();
        System.out.println("=== LISTADO DE PACIENTES ===");
        System.out.printf("%-20s %-15s %-10s %-10s %-15s %s%n", 
            "Nombre", "Documento", "Cuenta", "Tipo Sangre", "Nacimiento", "Alergias");
        
        pacientes.forEach(p -> {
            System.out.printf("%-20s %-15s %-10s %-10s %-15s %s%n", 
                p.getNombre(),
                p.getIdentificacion(),
                p.getCuenta(),
                p.getTipoSangre(),
                p.getFechaNacimiento(),
                p.getAlergias());
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al cargar pacientes: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        crearmedico = new javax.swing.JMenu();
        CrearPaciente = new javax.swing.JMenuItem();
        crearmedic = new javax.swing.JMenuItem();
        crearadmin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acceso Administrativo");

        jLabel2.setText("usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jMenu1.setText("Usuario");

        jMenuItem1.setText("Cambiar de Usuario ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Servicio");

        jMenuItem3.setText("Agendar Cita  ");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        crearmedico.setText("Crear Perfil ");

        CrearPaciente.setText("Paciente");
        CrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPacienteActionPerformed(evt);
            }
        });
        crearmedico.add(CrearPaciente);

        crearmedic.setText("Médico");
        crearmedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearmedicActionPerformed(evt);
            }
        });
        crearmedico.add(crearmedic);

        crearadmin.setText("Administrativo");
        crearadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearadminActionPerformed(evt);
            }
        });
        crearmedico.add(crearadmin);

        jMenuBar1.add(crearmedico);

        jMenu4.setText("Historial");

        jMenuItem7.setText("Paciente");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Médico");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void crearmedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearmedicActionPerformed
      
        // ######## Registrar nuevo Medico
        
        
        String nombre = JOptionPane.showInputDialog("Nombre del médico:");
        String identificacion = JOptionPane.showInputDialog("Identificación:");
        String cuentasin = JOptionPane.showInputDialog("Cuenta sin @medic:");
        String clave1 = JOptionPane.showInputDialog("clave:");
        String clave2 = JOptionPane.showInputDialog("repetir clave:");
        String especialidad = JOptionPane.showInputDialog("Especialidad:");
        String cuenta = cuentasin + ("@medic");
        
        if(clave1.equals(clave2)){
        
        Medico nuevo = new Medico(nombre, identificacion, cuenta, 
                                   clave1, especialidad);
        if (manager.registrarMedico(nuevo)) {
            JOptionPane.showMessageDialog(this, "Médico registrado!");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }else{JOptionPane.showMessageDialog(this, "Las claves no coinciden", "Error", JOptionPane.ERROR_MESSAGE);}
        
        
        
    }//GEN-LAST:event_crearmedicActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        try {
            // Crear y mostrar nuevo frame
            VentanaPrincipal nuevoFrame = new VentanaPrincipal();
            nuevoFrame.setLocationRelativeTo(null); // Centrar en pantalla
            nuevoFrame.setVisible(true);

            // Cerrar el frame actual
            this.dispose();
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPacienteActionPerformed
        
        // ######## Registrar nuevo paciente
        String nombre = JOptionPane.showInputDialog("Nombre del paciente:");
        String identificacion = JOptionPane.showInputDialog("Identificación:");
        String cuentasin = JOptionPane.showInputDialog("Cuenta sin @paciente:");
        String tipoSangre = JOptionPane.showInputDialog("Tipo de sangre:");
        String FNacimiento = JOptionPane.showInputDialog("Fecha de Nacimiento:");
        String alergias = JOptionPane.showInputDialog("Alergias:");
        String cuenta = cuentasin + ("@paciente");
        
        Paciente nuevo = new Paciente(nombre, identificacion, cuenta, 
                                   tipoSangre, FNacimiento, alergias);
        
        if (manager.registrarPaciente(nuevo)) {
            JOptionPane.showMessageDialog(this, "Paciente registrado!");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
        
    }//GEN-LAST:event_CrearPacienteActionPerformed

    private void crearadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearadminActionPerformed
        
            // ######## Registrar nuevo Administrativo
        
        
        String nombre = JOptionPane.showInputDialog("Nombre del Admin:");
        String identificacion = JOptionPane.showInputDialog("Identificación:");
        String cuentasin = JOptionPane.showInputDialog("Cuenta sin @admin:");
        String clave1 = JOptionPane.showInputDialog("clave:");
        String clave2 = JOptionPane.showInputDialog("repetir clave:");
        String cargo = JOptionPane.showInputDialog("cargo:");
        String cuenta = cuentasin + ("@admin");
        
        if(clave1.equals(clave2)){
        
        Administrativomodel nuevo = new Administrativomodel(nombre, identificacion, cuenta, 
                                   clave1, cargo);
        if (manager.registrarAdmin(nuevo)) {
            JOptionPane.showMessageDialog(this, "Administrativo registrado!");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }else{JOptionPane.showMessageDialog(this, "Las claves no coinciden", "Error", JOptionPane.ERROR_MESSAGE);}
        
        
    
    }//GEN-LAST:event_crearadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrativomodel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrativomodel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrativomodel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrativomodel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CrearPaciente;
    private javax.swing.JMenuItem crearadmin;
    private javax.swing.JMenuItem crearmedic;
    private javax.swing.JMenu crearmedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
